### PR TITLE
Update feedstock to fortranformat 1.2.0

### PR DESCRIPTION
**Pull request by alexmalins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This feedstock hasn't been updated in a while. Happy to become a maintainer if you'd like help on this feedstock.

### CODE REVIEW

**Review by smithsp — APPROVED** [review]
I verified that the new repo and documentation sites are correct.  Thanks for the PR.

**Comment by alexmalins** [comment]
Thanks @smithsp !

Just leaving a note here that this recipe could be improved by better testing - currently there is only an import test. However the default fortranformat test suite is slow - it took over an hour to run locally on my machine, not a good use of CI resources. Running a smaller selection of the tests is something that could be considered for the future.

**Comment by smithsp** [comment]
@alexmalins

Thanks for the feedback.  

Would you like to be listed as a maintainer of this feedstock?

**Comment by alexmalins** [comment]
Sure 👌

**Pull request merged**
